version: '3'
services:
  mlflow-server:
    image: mlflow_image
    build:
      context: . 
      dockerfile: ./mlflow.Dockerfile
    expose:
     - 5000
    ports:
     - 5000:5000  
    volumes:
     - mlflow-data:/mlflow-server
  duration-predictor:
    image: duration-predictor_image
    build:
      context: .
      dockerfile: ./gunicorn.Dockerfile
    ports:
     - 9696:9696
    expose:
     - 9696
    volumes:
     - duration-predictor-data:/mlops_bootcamp
    depends_on:
     - "mlflow-server"
    environment:
      MLFLOW_TRACKING_URI: 'http://mlflow-server:5000'
      MLFLOW_EXPERIMENT_NAME: 'gradient-booster-experiment-2'
volumes:
  mlflow-data:
    driver: local
  duration-predictor-data:
    driver: local
